# Uses the same default network
# We can curl inside nginx using blue:3001 or green:3002

services:
  blue:
    image: blue-green-app:blue
    ports:
      - "3001:3000"
    environment:
      - APP_VERSION=v1
  green:
    image: blue-green-app:green
    ports:
      - "3002:3000"
    environment:
      - APP_VERSION=v2
  nginx:
    image: nginx:latest
    ports: 
    - "8080:80"
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d #local:remote